import html
from datetime import datetime
from typing import Dict, Any


def bullet_list(items):
    if not items:
        return "<li>None specified</li>"

    return "\n".join(f"<li>{html.escape(str(item))}</li>" for item in items)


def render_minutes_html(data: Dict[str, Any], meeting_title: str, mode: str) -> str:

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    summary_items = bullet_list(data.get("meeting_summary", []))

    decision_items = ""

    for decision in data.get("key_decisions", []):

        decision_items += f"""
        <li>
            {html.escape(decision.get("decision", ""))}
            <i>
                (confidence:
                {html.escape(decision.get("confidence", ""))})
            </i>
        </li>
        """

    if not decision_items:
        decision_items = "<li>None specified</li>"

    action_rows = ""

    for item in data.get("action_items", []):

        action_rows += f"""
        <tr>
            <td>{html.escape(item.get("owner", ""))}</td>
            <td>{html.escape(item.get("task", ""))}</td>
            <td>{html.escape(item.get("deadline", ""))}</td>
            <td>{html.escape(item.get("confidence", ""))}</td>
        </tr>
        """

    if not action_rows:
        action_rows = """
        <tr>
            <td colspan="4">
                No action items specified
            </td>
        </tr>
        """

    topic_items = ""

    for topic in data.get("main_topics", []):

        topic_items += f"""
        <li>
            <b>{html.escape(topic.get("topic", ""))}:</b>
            {html.escape(topic.get("summary", ""))}
        </li>
        """

    if not topic_items:
        topic_items = "<li>None specified</li>"

    open_questions = bullet_list(data.get("open_questions", []))

    risks = bullet_list(data.get("risks_or_uncertainties", []))

    follow_up_required = "Yes" if data.get("follow_up_required") else "No"

    follow_up_reason = html.escape(data.get("follow_up_reason", ""))

    html_output = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    <title>
        {html.escape(meeting_title)}
    </title>

    <style>

        body {{
            font-family: Arial, sans-serif;
            margin: 40px;
            line-height: 1.5;
            color: #222;
        }}

        h1 {{
            color: #1f4e79;
        }}

        h2 {{
            margin-top: 35px;
            color: #2f75b5;
        }}

        table {{
            border-collapse: collapse;
            width: 100%;
            margin-top: 10px;
        }}

        th, td {{
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
        }}

        th {{
            background-color: #f2f2f2;
        }}

        .meta {{
            color: #666;
            margin-bottom: 25px;
        }}

        .section {{
            margin-top: 30px;
        }}

    </style>

</head>

<body>

    <h1>
        {html.escape(meeting_title)}
    </h1>

    <div class="meta">

        <p>
            <b>Generated at:</b>
            {generated_at}
        </p>

        <p>
            <b>Mode:</b>
            {html.escape(mode)}
        </p>

        <p>
            <b>Generated by:</b>
            AI Meeting Minutes Agent MVP
        </p>

    </div>

    <div class="section">

        <h2>
            Meeting Summary
        </h2>

        <ul>
            {summary_items}
        </ul>

    </div>

    <div class="section">

        <h2>
            Key Decisions
        </h2>

        <ul>
            {decision_items}
        </ul>

    </div>

    <div class="section">

        <h2>
            Action Items
        </h2>

        <table>

            <tr>
                <th>Owner</th>
                <th>Task</th>
                <th>Deadline</th>
                <th>Confidence</th>
            </tr>

            {action_rows}

        </table>

    </div>

    <div class="section">

        <h2>
            Main Discussion Topics
        </h2>

        <ul>
            {topic_items}
        </ul>

    </div>

    <div class="section">

        <h2>
            Open Questions
        </h2>

        <ul>
            {open_questions}
        </ul>

    </div>

    <div class="section">

        <h2>
            Follow-up
        </h2>

        <p>
            <b>Required:</b>
            {follow_up_required}
        </p>

        <p>
            {follow_up_reason}
        </p>

    </div>

    <div class="section">

        <h2>
            Risks / Uncertainties
        </h2>

        <ul>
            {risks}
        </ul>

    </div>

</body>
</html>
"""

    return html_output


def render_plain_text(data: Dict[str, Any], meeting_title: str) -> str:

    lines = []

    lines.append(f"# {meeting_title}")
    lines.append("")

    lines.append("## Meeting Summary")

    for item in data.get("meeting_summary", []):
        lines.append(f"- {item}")

    lines.append("")
    lines.append("## Key Decisions")

    for decision in data.get("key_decisions", []):

        lines.append(
            f"- {decision.get('decision')} "
            f"(confidence: {decision.get('confidence')})"
        )

    lines.append("")
    lines.append("## Action Items")

    for action in data.get("action_items", []):

        lines.append(
            f"- Owner: {action.get('owner')} | "
            f"Task: {action.get('task')} | "
            f"Deadline: {action.get('deadline')} | "
            f"Confidence: {action.get('confidence')}"
        )

    lines.append("")
    lines.append("## Main Discussion Topics")

    for topic in data.get("main_topics", []):

        lines.append(f"- {topic.get('topic')}: " f"{topic.get('summary')}")

    lines.append("")
    lines.append("## Open Questions")

    for question in data.get("open_questions", []):
        lines.append(f"- {question}")

    lines.append("")
    lines.append("## Follow-up")

    lines.append(f"Required: " f"{'Yes' if data.get('follow_up_required') else 'No'}")

    lines.append(data.get("follow_up_reason", ""))

    lines.append("")
    lines.append("## Risks / Uncertainties")

    for risk in data.get("risks_or_uncertainties", []):
        lines.append(f"- {risk}")

    return "\n".join(lines)
