import html
from datetime import datetime
from typing import Dict, Any

LABELS = {
    "English": {
        "generated_at": "Generated at",
        "mode": "Mode",
        "generated_by": "Generated by",
        "meeting_summary": "Meeting Summary",
        "key_decisions": "Key Decisions",
        "action_items": "Action Items",
        "owner": "Owner",
        "task": "Task",
        "deadline": "Deadline",
        "confidence": "Confidence",
        "main_topics": "Main Discussion Topics",
        "open_questions": "Open Questions",
        "follow_up": "Follow-up",
        "required": "Required",
        "risks": "Risks / Uncertainties",
        "none": "None specified",
        "no_actions": "No action items specified",
        "yes": "Yes",
        "no": "No",
    },
    "German": {
        "generated_at": "Erstellt am",
        "mode": "Modus",
        "generated_by": "Erstellt von",
        "meeting_summary": "Zusammenfassung",
        "key_decisions": "Wichtige Entscheidungen",
        "action_items": "Aufgaben",
        "owner": "Verantwortlich",
        "task": "Aufgabe",
        "deadline": "Frist",
        "confidence": "Sicherheit",
        "main_topics": "Hauptthemen",
        "open_questions": "Offene Fragen",
        "follow_up": "Nachverfolgung",
        "required": "Erforderlich",
        "risks": "Risiken / Unsicherheiten",
        "none": "Nicht angegeben",
        "no_actions": "Keine Aufgaben angegeben",
        "yes": "Ja",
        "no": "Nein",
    },
    "Italian": {
        "generated_at": "Generato il",
        "mode": "Modalità",
        "generated_by": "Generato da",
        "meeting_summary": "Sintesi della riunione",
        "key_decisions": "Decisioni principali",
        "action_items": "Azioni da svolgere",
        "owner": "Responsabile",
        "task": "Attività",
        "deadline": "Scadenza",
        "confidence": "Affidabilità",
        "main_topics": "Principali temi discussi",
        "open_questions": "Questioni aperte",
        "follow_up": "Follow-up",
        "required": "Richiesto",
        "risks": "Rischi / Incertezze",
        "none": "Non specificato",
        "no_actions": "Nessuna azione specificata",
        "yes": "Sì",
        "no": "No",
    },
    "Russian": {
        "generated_at": "Создано",
        "mode": "Режим",
        "generated_by": "Создано с помощью",
        "meeting_summary": "Краткое содержание встречи",
        "key_decisions": "Ключевые решения",
        "action_items": "Задачи",
        "owner": "Ответственный",
        "task": "Задача",
        "deadline": "Срок",
        "confidence": "Уверенность",
        "main_topics": "Основные темы обсуждения",
        "open_questions": "Открытые вопросы",
        "follow_up": "Дальнейшие действия",
        "required": "Требуется",
        "risks": "Риски / Неясности",
        "none": "Не указано",
        "no_actions": "Задачи не указаны",
        "yes": "Да",
        "no": "Нет",
    },
}


def get_labels(output_language: str) -> dict:
    return LABELS.get(output_language, LABELS["English"])


def bullet_list(items, none_label="None specified"):
    if not items:
        return f"<li>{html.escape(none_label)}</li>"

    return "\n".join(f"<li>{html.escape(str(item))}</li>" for item in items)


def render_minutes_html(
    data: Dict[str, Any],
    meeting_title: str,
    mode: str,
    output_language: str = "English",
) -> str:

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    labels = get_labels(output_language)

    summary_items = bullet_list(data.get("meeting_summary", []), labels["none"])

    decision_items = ""

    for decision in data.get("key_decisions", []):

        decision_items += f"""
        <li>
            {html.escape(decision.get("decision", ""))}
            <i>
                ({labels["confidence"]}:
                {html.escape(decision.get("confidence", ""))})
            </i>
        </li>
        """

    if not decision_items:
        decision_items = f"<li>{labels['none']}</li>"

    action_rows = ""

    for item in data.get("action_items", []):

        action_rows += f"""
        <tr>
            <td>{html.escape(item.get("owner", ""))}</td>
            <td>{html.escape(item.get("task", ""))}</td>
            <td>{html.escape(item.get("deadline", ""))}</td>
            <td>{html.escape(item.get("confidence", ""))}</td>
        </tr>
        """

    if not action_rows:
        action_rows = f"""
        <tr>
            <td colspan="4">
                {labels["no_actions"]}
            </td>
        </tr>
        """

    topic_items = ""

    for topic in data.get("main_topics", []):

        topic_items += f"""
        <li>
            <b>{html.escape(topic.get("topic", ""))}:</b>
            {html.escape(topic.get("summary", ""))}
        </li>
        """

    if not topic_items:
        topic_items = f"<li>{labels['none']}</li>"

    open_questions = bullet_list(data.get("open_questions", []), labels["none"])

    risks = bullet_list(data.get("risks_or_uncertainties", []), labels["none"])

    follow_up_required = (
        labels["yes"] if data.get("follow_up_required") else labels["no"]
    )

    follow_up_reason = html.escape(data.get("follow_up_reason", ""))

    html_output = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    <title>
        {html.escape(meeting_title)}
    </title>

    <style>

        body {{
            font-family: Arial, sans-serif;
            margin: 40px;
            line-height: 1.5;
            color: #222;
        }}

        h1 {{
            color: #1f4e79;
        }}

        h2 {{
            margin-top: 35px;
            color: #2f75b5;
        }}

        table {{
            border-collapse: collapse;
            width: 100%;
            margin-top: 10px;
        }}

        th, td {{
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
        }}

        th {{
            background-color: #f2f2f2;
        }}

        .meta {{
            color: #666;
            margin-bottom: 25px;
        }}

        .section {{
            margin-top: 30px;
        }}

    </style>

</head>

<body>

    <h1>
        {html.escape(meeting_title)}
    </h1>

    <div class="meta">

        <p>
            <b>{labels["generated_at"]}:</b>
            {generated_at}
        </p>

        <p>
            <b>{labels["mode"]}:</b>
            {html.escape(mode)}
        </p>

        <p>
            <b>{labels["generated_by"]}:</b>
            AI Meeting Minutes Agent MVP
        </p>

    </div>

    <div class="section">

        <h2>
            {labels["meeting_summary"]}
        </h2>

        <ul>
            {summary_items}
        </ul>

    </div>

    <div class="section">

        <h2>
            {labels["key_decisions"]}
        </h2>

        <ul>
            {decision_items}
        </ul>

    </div>

    <div class="section">

        <h2>
            {labels["action_items"]}
        </h2>

        <table>

            <tr>
                <th>{labels["owner"]}</th>
                <th>{labels["task"]}</th>
                <th>{labels["deadline"]}</th>
                <th>{labels["confidence"]}</th>
            </tr>

            {action_rows}

        </table>

    </div>

    <div class="section">

        <h2>
            {labels["main_topics"]}
        </h2>

        <ul>
            {topic_items}
        </ul>

    </div>

    <div class="section">

        <h2>
            {labels["open_questions"]}
        </h2>

        <ul>
            {open_questions}
        </ul>

    </div>

    <div class="section">

        <h2>
            {labels["follow_up"]}
        </h2>

        <p>
            <b>{labels["required"]}:</b>
            {follow_up_required}
        </p>

        <p>
            {follow_up_reason}
        </p>

    </div>

    <div class="section">

        <h2>
            {labels["risks"]}
        </h2>

        <ul>
            {risks}
        </ul>

    </div>

</body>
</html>
"""

    return html_output


def render_plain_text(
    data: Dict[str, Any], meeting_title: str, output_language: str = "English"
) -> str:

    labels = get_labels(output_language)

    lines = []

    lines.append(f"# {meeting_title}")
    lines.append("")

    lines.append(f"## {labels['meeting_summary']}")

    for item in data.get("meeting_summary", []):
        lines.append(f"- {item}")

    lines.append("")
    lines.append(f"## {labels['key_decisions']}")

    for decision in data.get("key_decisions", []):

        lines.append(
            f"- {decision.get('decision')} "
            f"({labels['confidence']}: {decision.get('confidence')})"
        )

    lines.append("")
    lines.append(f"## {labels['action_items']}")

    for action in data.get("action_items", []):

        lines.append(
            f"- {labels['owner']}: {action.get('owner')} | "
            f"{labels['task']}: {action.get('task')} | "
            f"{labels['deadline']}: {action.get('deadline')} | "
            f"{labels['confidence']}: {action.get('confidence')}"
        )

    lines.append("")
    lines.append(f"## {labels['main_topics']}")

    for topic in data.get("main_topics", []):

        lines.append(f"- {topic.get('topic')}: " f"{topic.get('summary')}")

    lines.append("")
    lines.append(f"## {labels['open_questions']}")

    for question in data.get("open_questions", []):
        lines.append(f"- {question}")

    lines.append("")
    lines.append(f"## {labels['follow_up']}")

    lines.append(
        f"{labels['required']}: "
        f"{labels['yes'] if data.get('follow_up_required') else labels['no']}"
    )

    lines.append(data.get("follow_up_reason", ""))

    lines.append("")
    lines.append(f"## {labels['risks']}")

    for risk in data.get("risks_or_uncertainties", []):
        lines.append(f"- {risk}")

    return "\n".join(lines)
