from datetime import datetime

from microsoft_graph import (
    create_outlook_draft,
)


def build_followup_email_subject(
    meeting_title: str,
) -> str:
    meeting_title = meeting_title.strip()

    current_date = datetime.now().strftime("%Y-%m-%d")

    return f"Follow-up | {meeting_title} | {current_date}"


def build_followup_email_html(
    meeting_title: str,
    summary_html: str,
    created_by: str,
    meeting_link: str | None = None,
) -> str:
    created_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    meeting_link_html = ""

    if meeting_link:
        meeting_link_html = f"""
        <p>
            <strong>Meeting Link:</strong><br>
            <a href="{meeting_link}">
                {meeting_link}
            </a>
        </p>
        """

    return f"""
<html>
<body>

    <h2>Meeting Follow-up</h2>

    <p>
        This draft email was automatically generated by the
        AI Meeting Minutes Agent.
    </p>

    <hr>

    <p>
        <strong>Meeting:</strong> {meeting_title}
    </p>

    <p>
        <strong>Generated:</strong> {created_at}
    </p>

    <p>
        <strong>Generated By:</strong> {created_by}
    </p>

    {meeting_link_html}

    <hr>

    {summary_html}

</body>
</html>
"""


def create_followup_email_draft(
    access_token: str,
    meeting_title: str,
    summary_html: str,
    created_by: str,
    recipients: list[str],
    meeting_link: str | None = None,
) -> dict:
    subject = build_followup_email_subject(
        meeting_title=meeting_title,
    )

    body_html = build_followup_email_html(
        meeting_title=meeting_title,
        summary_html=summary_html,
        created_by=created_by,
        meeting_link=meeting_link,
    )

    result = create_outlook_draft(
        access_token=access_token,
        subject=subject,
        body_html=body_html,
        to_recipients=recipients,
    )

    if not result["success"]:
        return {
            "success": False,
            "error": result.get("error"),
            "details": result,
        }

    data = result["data"]

    return {
        "success": True,
        "draft_id": data.get("id"),
        "subject": data.get("subject"),
        "web_link": data.get("webLink"),
        "raw_result": data,
    }