from auth_service import (
    get_auth_url,
    authenticate_user,
)

from outlook_service import (
    create_followup_email_draft,
)

print("\nOPEN THIS URL:\n")
print(get_auth_url())

print("\nAfter login copy only the value after code=\n")

auth_code = input("Paste authorization code:\n").strip()

auth_result = authenticate_user(auth_code)

print("\nAUTH RESULT:\n")
print(auth_result)

if not auth_result["success"]:
    raise SystemExit

access_token = auth_result["access_token"]

identity = auth_result["identity"]

summary_html = """
<h2>Executive Summary</h2>

<p>
This is a test follow-up generated by the AI Meeting Minutes Agent.
</p>

<h2>Action Items</h2>

<ul>
    <li>Review Microsoft architecture</li>
    <li>Prepare pilot workflow</li>
    <li>Validate OneNote integration</li>
</ul>
"""

result = create_followup_email_draft(
    access_token=access_token,
    meeting_title="AI Agent Architecture Discussion",
    summary_html=summary_html,
    created_by=identity["email"],
    recipients=["office@nrgeer.com"],
    meeting_link="https://teams.microsoft.com/test-link",
)

print("\nOUTLOOK RESULT:\n")
print(result)
